project_id = "irqfyjrlpfpdjztvxahs"

[functions.chat]
verify_jwt = true

[functions.solve-image]
verify_jwt = true

[functions.convert-pdf-mcq]
verify_jwt = true

[functions.smart-summary]
verify_jwt = true

[functions.generate-diagram]
verify_jwt = true
