project_id = "irqfyjrlpfpdjztvxahs"

[functions.chat]
verify_jwt = false

[functions.solve-image]
verify_jwt = false

[functions.convert-pdf-mcq]
verify_jwt = false

[functions.smart-summary]
verify_jwt = false

[functions.generate-diagram]
verify_jwt = false